"""
Database module for QuizMaster - Phase 2
Handles SQLite database operations, user authentication, and CRUD for questions/scores
"""

import sqlite3
from pathlib import Path
import hashlib
import json
import os

DATABASE_PATH = Path(__file__).parent / "data" / "quizmaster.db"
QUESTIONS_JSON_PATH = Path(__file__).parent / "data" / "questions.json"
DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
IS_POSTGRES = DATABASE_URL.startswith("postgres://") or DATABASE_URL.startswith("postgresql://")

if IS_POSTGRES:
    try:
        import psycopg2
        from psycopg2.extras import RealDictCursor
    except Exception as e:
        raise RuntimeError(
            "DATABASE_URL is set but psycopg2 is not installed. "
            "Add psycopg2-binary to requirements.txt."
        ) from e


def get_connection():
    if IS_POSTGRES:
        conn = psycopg2.connect(
            DATABASE_URL,
            cursor_factory=RealDictCursor,
            sslmode=os.getenv("DB_SSLMODE", "require"),
        )
    else:
        conn = sqlite3.connect(DATABASE_PATH)
        conn.row_factory = sqlite3.Row
    return conn


def _sql(query):
    if IS_POSTGRES:
        return query.replace("?", "%s")
    return query


def _export_questions_to_json():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        """
        SELECT id, category, question, options, correct_index, difficulty, points
        FROM questions
        ORDER BY category, id
    """
    )
    rows = cursor.fetchall()
    conn.close()

    categories = {}
    per_category_index = {}
    for row in rows:
        category = row["category"]
        per_category_index[category] = per_category_index.get(category, 0) + 1
        categories.setdefault(category, []).append(
            {
                "id": per_category_index[category],
                "question": row["question"],
                "options": json.loads(row["options"]),
                "correct": row["correct_index"],
                "difficulty": row["difficulty"] or "medium",
                "points": row["points"] if row["points"] is not None else 10,
            }
        )

    payload = {"categories": categories}
    QUESTIONS_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(QUESTIONS_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def init_database():
    conn = get_connection()
    cursor = conn.cursor()
    if IS_POSTGRES:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                is_admin BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS questions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                category TEXT NOT NULL,
                question TEXT NOT NULL,
                options TEXT NOT NULL,
                correct_index INTEGER NOT NULL,
                difficulty TEXT DEFAULT 'medium',
                points INTEGER DEFAULT 10,
                created_by BIGINT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (created_by) REFERENCES users(id)
            )
        """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS scores (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                category TEXT NOT NULL,
                score INTEGER NOT NULL,
                correct_answers INTEGER NOT NULL,
                total_questions INTEGER NOT NULL,
                percentage REAL NOT NULL,
                played_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users(id)
            )
        """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sender_id BIGINT NOT NULL,
                receiver_id BIGINT NOT NULL,
                category TEXT,
                message TEXT NOT NULL,
                sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (sender_id) REFERENCES users(id),
                FOREIGN KEY (receiver_id) REFERENCES users(id)
            )
        """
        )
    else:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                is_admin BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS questions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                category TEXT NOT NULL,
                question TEXT NOT NULL,
                options TEXT NOT NULL,
                correct_index INTEGER NOT NULL,
                difficulty TEXT DEFAULT 'medium',
                points INTEGER DEFAULT 10,
                created_by INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (created_by) REFERENCES users(id)
            )
        """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS scores (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                category TEXT NOT NULL,
                score INTEGER NOT NULL,
                correct_answers INTEGER NOT NULL,
                total_questions INTEGER NOT NULL,
                percentage REAL NOT NULL,
                played_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users(id)
            )
        """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS messages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                sender_id INTEGER NOT NULL,
                receiver_id INTEGER NOT NULL,
                category TEXT,
                message TEXT NOT NULL,
                sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (sender_id) REFERENCES users(id),
                FOREIGN KEY (receiver_id) REFERENCES users(id)
            )
        """
        )
    conn.commit()
    conn.close()


def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()


def create_user(username, password, is_admin=False):
    if not username or not password:
        return False, "Username and password are required"
    if len(password) < 6:
        return False, "Password must be at least 6 characters"
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            _sql("INSERT INTO users (username, password_hash, is_admin) VALUES (?, ?, ?)"),
            (username, hash_password(password), is_admin),
        )
        conn.commit()
        return True, "User created successfully"
    except sqlite3.IntegrityError:
        return False, "Username already exists"
    except Exception as e:
        if "unique" in str(e).lower() or "duplicate" in str(e).lower():
            return False, "Username already exists"
        raise
    finally:
        conn.close()


def verify_user(username, password):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        _sql("SELECT * FROM users WHERE username = ? AND password_hash = ?"),
        (username, hash_password(password)),
    )
    row = cursor.fetchone()
    conn.close()
    if row:
        return {
            "id": row["id"],
            "username": row["username"],
            "is_admin": bool(row["is_admin"]),
            "created_at": row["created_at"],
        }
    return None


def ensure_admin_account(username="admin", password="admin123mas"):
    """
    Ensure there is a default admin account with the expected credentials.
    If the user exists, force admin privileges and update password hash.
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(_sql("SELECT id FROM users WHERE username = ?"), (username,))
    row = cursor.fetchone()
    password_hash = hash_password(password)
    if row:
        cursor.execute(
            _sql("UPDATE users SET password_hash = ?, is_admin = 1 WHERE username = ?"),
            (password_hash, username),
        )
    else:
        cursor.execute(
            _sql("INSERT INTO users (username, password_hash, is_admin) VALUES (?, ?, 1)"),
            (username, password_hash),
        )
    conn.commit()
    conn.close()


def get_user_by_id(user_id):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(_sql("SELECT * FROM users WHERE id = ?"), (user_id,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def get_user_by_username(username):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(_sql("SELECT * FROM users WHERE username = ?"), (username,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def get_all_usernames(exclude_user_id=None):
    conn = get_connection()
    cursor = conn.cursor()
    if exclude_user_id:
        cursor.execute(_sql("SELECT username FROM users WHERE id != ? ORDER BY username"), (exclude_user_id,))
    else:
        cursor.execute("SELECT username FROM users ORDER BY username")
    rows = cursor.fetchall()
    conn.close()
    return [row["username"] for row in rows]


def get_all_users_with_activity():
    conn = get_connection()
    cursor = conn.cursor()
    if IS_POSTGRES:
        cursor.execute(
            """
            SELECT
                u.id,
                u.username,
                u.is_admin,
                u.created_at,
                COALESCE(s.quizzes_taken, 0) AS quizzes_taken,
                GREATEST(
                    COALESCE(s.last_score_at, u.created_at),
                    COALESCE(m.last_message_at, u.created_at)
                ) AS last_online
            FROM users u
            LEFT JOIN (
                SELECT
                    user_id,
                    COUNT(*) AS quizzes_taken,
                    MAX(played_at) AS last_score_at
                FROM scores
                GROUP BY user_id
            ) s ON s.user_id = u.id
            LEFT JOIN (
                SELECT
                    user_id,
                    MAX(activity_at) AS last_message_at
                FROM (
                    SELECT sender_id AS user_id, sent_at AS activity_at FROM messages
                    UNION ALL
                    SELECT receiver_id AS user_id, sent_at AS activity_at FROM messages
                ) activity
                GROUP BY user_id
            ) m ON m.user_id = u.id
            ORDER BY u.created_at DESC, u.username ASC
        """
        )
    else:
        cursor.execute(
            """
            SELECT
                u.id,
                u.username,
                u.is_admin,
                u.created_at,
                COALESCE(s.quizzes_taken, 0) AS quizzes_taken,
                MAX(
                    COALESCE(s.last_score_at, u.created_at),
                    COALESCE(m.last_message_at, u.created_at)
                ) AS last_online
            FROM users u
            LEFT JOIN (
                SELECT
                    user_id,
                    COUNT(*) AS quizzes_taken,
                    MAX(played_at) AS last_score_at
                FROM scores
                GROUP BY user_id
            ) s ON s.user_id = u.id
            LEFT JOIN (
                SELECT
                    user_id,
                    MAX(activity_at) AS last_message_at
                FROM (
                    SELECT sender_id AS user_id, sent_at AS activity_at FROM messages
                    UNION ALL
                    SELECT receiver_id AS user_id, sent_at AS activity_at FROM messages
                )
                GROUP BY user_id
            ) m ON m.user_id = u.id
            ORDER BY u.created_at DESC, u.username ASC
        """
        )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def add_question(
    category, question, options, correct_index, difficulty="medium", points=10, created_by=None
):
    conn = get_connection()
    cursor = conn.cursor()
    if IS_POSTGRES:
        cursor.execute(
            _sql(
                """
                INSERT INTO questions
                (category, question, options, correct_index, difficulty, points, created_by)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                RETURNING id
            """
            ),
            (category, question, json.dumps(options), correct_index, difficulty, points, created_by),
        )
        question_id = cursor.fetchone()["id"]
    else:
        cursor.execute(
            _sql(
                """
                INSERT INTO questions
                (category, question, options, correct_index, difficulty, points, created_by)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """
            ),
            (category, question, json.dumps(options), correct_index, difficulty, points, created_by),
        )
        question_id = cursor.lastrowid
    conn.commit()
    conn.close()
    _export_questions_to_json()
    return question_id


def get_questions_by_category(category):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(_sql("SELECT * FROM questions WHERE category = ? ORDER BY id"), (category,))
    rows = cursor.fetchall()
    conn.close()
    return [
        {
            "id": row["id"],
            "category": row["category"],
            "question": row["question"],
            "options": json.loads(row["options"]),
            "correct": row["correct_index"],
            "difficulty": row["difficulty"],
            "points": row["points"],
            "created_by": row["created_by"],
            "created_at": row["created_at"],
        }
        for row in rows
    ]


def get_all_categories():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT DISTINCT category FROM questions ORDER BY category")
    rows = cursor.fetchall()
    conn.close()
    return [row["category"] for row in rows]


def get_category_creators(category):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        _sql(
            """
        SELECT DISTINCT u.username
        FROM questions q
        LEFT JOIN users u ON q.created_by = u.id
        WHERE q.category = ?
        ORDER BY u.username
    """
        ),
        (category,),
    )
    rows = cursor.fetchall()
    conn.close()
    creators = [row["username"] for row in rows if row["username"]]
    if not creators:
        return ["System"]
    return creators


def get_question_by_id(question_id):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(_sql("SELECT * FROM questions WHERE id = ?"), (question_id,))
    row = cursor.fetchone()
    conn.close()
    if row:
        return {
            "id": row["id"],
            "category": row["category"],
            "question": row["question"],
            "options": json.loads(row["options"]),
            "correct": row["correct_index"],
            "difficulty": row["difficulty"],
            "points": row["points"],
            "created_by": row["created_by"],
        }
    return None


def update_question(
    question_id, category=None, question=None, options=None, correct_index=None, difficulty=None, points=None
):
    conn = get_connection()
    cursor = conn.cursor()
    updates, values = [], []
    if category is not None:
        updates.append("category = ?")
        values.append(category)
    if question is not None:
        updates.append("question = ?")
        values.append(question)
    if options is not None:
        updates.append("options = ?")
        values.append(json.dumps(options))
    if correct_index is not None:
        updates.append("correct_index = ?")
        values.append(correct_index)
    if difficulty is not None:
        updates.append("difficulty = ?")
        values.append(difficulty)
    if points is not None:
        updates.append("points = ?")
        values.append(points)
    if not updates:
        conn.close()
        return False
    values.append(question_id)
    cursor.execute(_sql(f"UPDATE questions SET {', '.join(updates)} WHERE id = ?"), values)
    conn.commit()
    success = cursor.rowcount > 0
    conn.close()
    if success:
        _export_questions_to_json()
    return success


def delete_question(question_id):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(_sql("DELETE FROM questions WHERE id = ?"), (question_id,))
    conn.commit()
    success = cursor.rowcount > 0
    conn.close()
    if success:
        _export_questions_to_json()
    return success


def save_score(user_id, category, score, correct_answers, total_questions):
    conn = get_connection()
    cursor = conn.cursor()
    percentage = (correct_answers / total_questions * 100) if total_questions > 0 else 0
    cursor.execute(
        _sql(
            """
        INSERT INTO scores
        (user_id, category, score, correct_answers, total_questions, percentage)
        VALUES (?, ?, ?, ?, ?, ?)
    """
        ),
        (user_id, category, score, correct_answers, total_questions, percentage),
    )
    conn.commit()
    conn.close()


def get_highscores(limit=10, category=None):
    conn = get_connection()
    cursor = conn.cursor()
    if category:
        cursor.execute(
            _sql(
                """
            SELECT s.*, u.username
            FROM scores s
            JOIN users u ON s.user_id = u.id
            WHERE s.category = ?
            ORDER BY s.score DESC, s.played_at DESC
            LIMIT ?
        """
            ),
            (category, limit),
        )
    else:
        cursor.execute(
            _sql(
                """
            SELECT s.*, u.username
            FROM scores s
            JOIN users u ON s.user_id = u.id
            ORDER BY s.score DESC, s.played_at DESC
            LIMIT ?
        """
            ),
            (limit,),
        )
    rows = cursor.fetchall()
    conn.close()
    return [
        {
            "id": row["id"],
            "username": row["username"],
            "user_id": row["user_id"],
            "category": row["category"],
            "score": row["score"],
            "correct_answers": row["correct_answers"],
            "total_questions": row["total_questions"],
            "percentage": row["percentage"],
            "played_at": row["played_at"],
        }
        for row in rows
    ]


def get_user_scores(user_id, limit=10):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        _sql(
            """
        SELECT * FROM scores WHERE user_id = ?
        ORDER BY played_at DESC LIMIT ?
    """
        ),
        (user_id, limit),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def get_user_statistics(user_id):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        _sql(
            """
        SELECT
            COUNT(*) as total_games,
            AVG(score) as avg_score,
            MAX(score) as best_score,
            AVG(percentage) as avg_percentage,
            SUM(correct_answers) as total_correct,
            SUM(total_questions) as total_questions
        FROM scores WHERE user_id = ?
    """
        ),
        (user_id,),
    )
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def send_message(sender_id, receiver_id, message, category=None):
    conn = get_connection()
    cursor = conn.cursor()
    if IS_POSTGRES:
        cursor.execute(
            """
            INSERT INTO messages (sender_id, receiver_id, category, message)
            VALUES (%s, %s, %s, %s)
            RETURNING id
        """,
            (sender_id, receiver_id, category, message),
        )
        message_id = cursor.fetchone()["id"]
    else:
        cursor.execute(
            _sql(
                """
            INSERT INTO messages (sender_id, receiver_id, category, message)
            VALUES (?, ?, ?, ?)
        """
            ),
            (sender_id, receiver_id, category, message),
        )
        message_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return message_id


def get_messages_for_user(user_id, limit=50):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        _sql(
            """
        SELECT
            m.id,
            m.category,
            m.message,
            m.sent_at,
            sender.username AS sender_username,
            receiver.username AS receiver_username
        FROM messages m
        JOIN users sender ON m.sender_id = sender.id
        JOIN users receiver ON m.receiver_id = receiver.id
        WHERE m.receiver_id = ?
        ORDER BY m.sent_at DESC
        LIMIT ?
    """
        ),
        (user_id, limit),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def get_all_messages(limit=200):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        _sql(
            """
        SELECT
            m.id,
            m.category,
            m.message,
            m.sent_at,
            sender.username AS sender_username,
            receiver.username AS receiver_username
        FROM messages m
        JOIN users sender ON m.sender_id = sender.id
        JOIN users receiver ON m.receiver_id = receiver.id
        ORDER BY m.sent_at DESC
        LIMIT ?
    """
        ),
        (limit,),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def migrate_json_to_db(questions_json_path):
    try:
        with open(questions_json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        count = 0
        for category, questions in data.get("categories", {}).items():
            for q in questions:
                add_question(
                    category=category,
                    question=q["question"],
                    options=q["options"],
                    correct_index=q["correct"],
                    difficulty=q.get("difficulty", "medium"),
                    points=q.get("points", 10),
                    created_by=None,
                )
                count += 1
        return count
    except Exception as e:
        print(f"Migration error: {e}")
        return 0


init_database()
ensure_admin_account()

conn = get_connection()
cursor = conn.cursor()
cursor.execute("SELECT COUNT(*) AS count FROM questions")
question_count = cursor.fetchone()["count"]
conn.close()

if question_count == 0 and QUESTIONS_JSON_PATH.exists():
    migrate_json_to_db(QUESTIONS_JSON_PATH)
